# Generated by Django 3.2.16 on 2022-11-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFS',
            fields=[
                ('id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, verbose_name='nfs id')),
                ('name', models.CharField(max_length=128, null=True)),
                ('subnet_id', models.CharField(max_length=36, null=True)),
                ('tenant_id', models.CharField(max_length=36, null=True)),
                ('cidr', models.CharField(max_length=36, null=True)),
                ('vlan_id', models.IntegerField(null=True)),
                ('ip', models.CharField(max_length=36, null=True)),
                ('port_id', models.CharField(max_length=36, null=True)),
                ('status', models.CharField(max_length=36, null=True)),
                ('nfs_id', models.IntegerField(null=True)),
                ('quota_id', models.CharField(max_length=36, null=True)),
            ],
        ),
    ]
