# Generated by Django 3.2.16 on 2022-11-03 08:34

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onefs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nfs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
    ]
